# Generated by Django 2.0.1 on 2018-01-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
