# Generated by Django 2.0.1 on 2018-01-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_deployment_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='webhook_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
