# Generated by Django 2.0.1 on 2018-01-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20180125_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='conatainer_id_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
