# Generated by Django 2.0.1 on 2018-01-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_deployment_conatainer_id_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='conatainer_id_text',
            new_name='container_id_text',
        ),
    ]
