# Generated by Django 2.0.1 on 2018-01-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_deployment_git_branch_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='domain_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
