# Generated by Django 2.0.1 on 2018-02-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_deployment_domain_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='is_compose',
            field=models.BooleanField(default=False),
        ),
    ]
